name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Cache Poetry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry
          ~/.venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
      shell: bash

    - name: Install dependencies
      run: |
        poetry lock --no-update
        poetry install --with dev
      shell: bash

    - name: Start the FastAPI server
      run: |
        nohup poetry run uvicorn src.app:app --host 0.0.0.0 --port 8000 &
        sleep 5  # Wait for server to start
      shell: bash

    - name: Run tests
      run: poetry run invoke test
      shell: bash

    - name: Run linting
      run: poetry run invoke lint
      shell: bash

    - name: Run type checks
      run: poetry run invoke type-check
      shell: bash
