name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Setup Project
        uses: ./.github/actions/setup
        with:
          python-version: 3.12

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install pipx
          pipx install poetry
          poetry --version

      # Step 4: Install dependencies
      - name: Install dependencies
        run: poetry install

      - name: Start the FastAPI server
        run: |
          nohup poetry run uvicorn src.app:app --host 0.0.0.0 --port 8000 &
        shell: bash
                
      # Step 5: Run tests
      - name: Run tests
        run: poetry run invoke test

      # Step 6: Run linting
      - name: Run linting
        run: poetry run invoke lint

      # Step 7: Run typing checks
      - name: Run type checks
        run: poetry run invoke type
